INSERT INTO customer_sub_status (customerStatusId, title, description) VALUES (1, 'Cotizando', '');
INSERT INTO customer_sub_status (customerStatusId, title, description) VALUES (1, 'Interesado', '');
INSERT INTO customer_sub_status (customerStatusId, title, description) VALUES (1, 'Por pagar ', 'Agrega tu fecha posible de pago');
INSERT INTO customer_sub_status (customerStatusId, title, description) VALUES (2, 'Cuestionario Cliente', '');
INSERT INTO customer_sub_status (customerStatusId, title, description) VALUES (2, 'Traspaso información', '');
INSERT INTO customer_sub_status (customerStatusId, title, description) VALUES (3, 'En desarrollo', '');
INSERT INTO customer_sub_status (customerStatusId, title, description) VALUES (3, 'Entregado', '');
INSERT INTO customer_sub_status (customerStatusId, title, description) VALUES (3, 'Aprobado', '');
INSERT INTO customer_sub_status (customerStatusId, title, description) VALUES (4, 'En proceso', '');
INSERT INTO customer_sub_status (customerStatusId, title, description) VALUES (4, 'Entregado', '');
INSERT INTO customer_sub_status (customerStatusId, title, description) VALUES (4, 'Aprobado', '');
INSERT INTO customer_sub_status (customerStatusId, title, description) VALUES (5, 'En proceso', '');
INSERT INTO customer_sub_status (customerStatusId, title, description) VALUES (5, 'Entregado', '');
INSERT INTO customer_sub_status (customerStatusId, title, description) VALUES (6, 'Espera pago', '');